import = [
    "~/.config/alacritty/colorscheme-spooky.toml",
    "~/.config/alacritty/bindings.toml",
    "~/.config/alacritty/fontconfig.toml"
]

live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

# vim: ts=2 sts=2 sw=2 et
