# $bg: #1e1e2e;
# $bg-alt: #313244;
# $bg-alt-alt: #45475a;
# $fg: #cdd6f4;
# $red: #f38ba8;
# $green: #a6e3a1;
# $yellow: #f9e2af;
# $blue: #89b4fa;
# $purple: #cba6f7;
# $cyan: #74c7ec;
# $gray: #585b70;
# $gray-alt: #6c7086;
# $fg-alt: #bac2de;
# $red-alt: #ed8796;
# $green-alt: #a6da95;
# $yellow-alt: #eed49f;
# $orange: #ef9f76;
# $orange-alt: #f5a97f;
# $blue-alt: #8aadf4;
# $purple-alt: #c6a0f6;
# $cyan-alt: #91d7e3;
[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"
bright_foreground = "#f2d5cf"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#303446"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#cdd6f4"
background = "#1e1e2e"

[colors.search.focused_match]
foreground = "#cdd6f4"
background = "#1e1e2e"

[colors.footer_bar]
foreground = "#cdd6f4"
background = "#1e1e2e"

[colors.hints.start]
foreground = "#cdd6f4"
background = "#1e1e2e"

[colors.hints.end]
foreground = "#cdd6f4"
background = "#1e1e2e"

[colors.selection]
text = "#303446"
background = "#1e1e2e"

[colors.normal]
black = "#313244"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#74c7ec"
white = "#ccd6f4"

[colors.bright]
black = "#45475a"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#91d7e3"
white = "#ccd6f4"

[colors.dim]
black = "#313244"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#74c7ec"
white = "#585b70"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f2d5cf"

[[colors.indexed_colors]]
index = 18
color = "#cdd6f4"
