[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

