#! /bin/sh

sxhkd &
compton &
$HOME/.config/polybar/launch.sh &

bspc monitor -d term firefox spotify code V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a spotify desktop='^3'
