#!/usr/bin/env bash

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

bspc wm -O 2 1
bspc monitor "0x00400013" -d '1' '2' '3' '4' '5' '6'
bspc monitor "0x0040000A" -d  '7' '8' '9'

workspaces

bspc config external_rules_command "$HOME"/.config/bspwm/scripts/ExternalRules
bspc config border_width 0
bspc config top_padding 2
bspc config bottom_padding 2
bspc config normal_border_color "#414868"
bspc config active_border_color "#c0caf5"
bspc config focused_border_color "#bb9af7"
bspc config presel_feedback_color "#7aa2f7"
bspc config left_padding 2
bspc config right_padding 2
bspc config window_gap 8

bspc config split_ratio 0.55
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on
bspc rule -a '*:lxappearance' state=floating center=true
bspc rule -a nm-applet state=floating center=true
bspc rule -a Nm-connection-editor state=floating

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("xcompmgr" "polybar" "sxhkd" "dunst" "xss-lock")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done
#
# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

# Load bars 
#"$XDG_CONFIG_HOME"/polybar/launch.sh &

xcompmgr &

# Launch dunst notification daemon
dunst -conf "$XDG_CONFIG_HOME"/bspwm/dunstrc &

# Set random wallpaper for actual rice
setbg &


# Launch polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Fix cursor
xsetroot -cursor_name left_ptr &

#conky
#$HOME/.config/conky/Auva/start.sh &

#redshift
#redshift-gtk -l 3.597031:98.678513 -t 5700:3500 &

#tail -F $HOME/.config/bspwm/rices/ryan/scripts/tray-status 2> /dev/null &

#autolockscreen
# xss-lock /usr/local/bin/lock-screen &
#xautolock -time 10 -locker "$HOME/.config/bspwm/scripts/lock" && echo mem ? /sys/power/state &

#speedup pointer
xset r rate 300 50 &

pidof -s init &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start >/dev/null 2>&1

#music
mpd &
