#!/bin/sh

_viewGitLogLine="echo {} | 
                 grep -o '[a-f0-9]\{7\}' | 
                 head -1 | 
                 xargs -I % sh -c 'git show --color=always %'"
_gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}'"

function gcm() {
  git log \
    --color=always \
    --reverse \
    --format="%C(cyan)%h %C(blue)%ar%C(auto)%d ac%C(yellow)%s%+b %C(white)%ae" "$@" |
    fzf -i -e +s \
      --reverse \
      --tiebreak=index \
      --no-multi \
      --ansi \
      --preview="echo {} |
                 grep -o '[a-f0-9]\{7\}' |
                 head -1 |
                 xargs -I % sh -c 'git show --color=always %' |
                 bat" \
      --header "enter: view, C-c: copy hash" \
      --bind "enter:execute:$_viewGitLogLine | less -R" \
      --bind "ctrl-c:execute:$_gitLogLineToHash |
              xclip -r -selection clipboard" \
      --bind "ctrl-c:+accept"
}

_gitCheckoutBranch="echo {} | xargs -I % sh -c 'git checkout %'"

function gbr() {
  git branch \
    --color=always |
    fzf -i -e +s \
      --reverse \
      --tiebreak=index \
      --no-multi \
      --ansi \
      --header "enter: checkout, C-c: copy name" \
      --bind "enter:execute:$_gitCheckoutBranch" \
      --bind "enter:+close" \
      --bind "ctrl-c:execute:echo {} |
              xclip -r -selection clipboard" \
      --bind "ctrl-c:+accept"
}

function fpr() {
  cd "$(find ~/documents/projects/ -maxdepth 2 -type d -not -path '*/.*' -not -path '*node_modules*' -not -path '*/target/*' -not -path '*/build/*' | \
    fzf -i -e +s \
      --reverse \
      --tiebreak=index \
      --no-multi \
      --ansi \
      --header 'enter: GoTo' \
      --bind 'enter:accept')"
}
