require('plugins')
require('mappings')
require('globals')
require('settings')

require('pl-autocommands')
require('pl-treesitter')
require('pl-fzf')
require('pl-fugitive')
require('pl-lspinstall')
require('pl-whichkey')
require('pl-colorizer')

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')

require('lsp')
require('lsp.lsp-bash')
require('lsp.lsp-elm')
require('lsp.lsp-docker')
require('lsp.lsp-json')
require('lsp.lsp-kotlin')
require('lsp.lsp-latex')
require('lsp.lsp-lua')
require('lsp.lsp-python')
require('lsp.lsp-vim')
require('lsp.lsp-yaml')
